services:
  atlas:
    image: atlas:latest
    environment:
      - BODY_SIZE_LIMIT=Infinity

    build: .
    ports:
      - "3000:3000"
    volumes:
      - atlas-data:/app/data

volumes:
  atlas-data:
